apiVersion: v1
kind: Service
metadata:
  name: wordpress
  namespace: portalino-dev
spec:
  ports:
    - port: 5055
      targetPort: 80
      NodePort: 0
  selector:
   name: wp-svil
  type: LoadBalancer
